### ISSUE TITLE
Reactivity issue with Vue 2 but not Vue 3

### ISSUE THREAD

**Issue by kamnakis** [vueuse/vue-demi#102]
## Explanation

Hello there. I have a simple typescript package that uses `vue-demi`

```ts
// src/index.ts
import { ref } from 'vue-demi'

export function useTestPackage () {
  const hello = ref('Hello World')

  return {
    hello
  }
}
```
And my `pacakge.json`
```json
{
  "name": "test-ts-package",
  "version": "0.0.1",
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index.js",
  "types": "dist/esm/index.d.ts",
  "description": "",
  "scripts": {
    "build": "npx rimraf dist && npm run build:esm && npm run build:cjs",
    "build:esm": "tsc --module es2015 --outDir dist/esm -d",
    "build:cjs": "tsc --module commonjs --outDir dist/cjs",
    "serve": "npm run build && npm pack"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue-demi": "latest"
  },
  "devDependencies": {
    "@vue/composition-api": "^1.0.0-rc.1",
    "typescript": "^4.4.2",
    "vue": "^3.0.0"
  },
  "peerDependencies": {
    "@vue/composition-api": "^1.0.0-rc.1",
    "vue": "^2.0.0 || >=3.0.0"
  },
  "peerDependenciesMeta": {
    "@vue/composition-api": {
      "optional": true
    }
  }
}
```

I run `npm run serve` to build the project and pack it on a `.tgz` file for local installation

## Vue 3 Usage
In my Vue 3 App (Vite) I installed with local path `npm i ../test-ts-package/test-ts-package-0.0.1.tgz`

And in my page I have this
```vue
<template>
  <div>
    <h6>
      {{ hello }}
      <button @click="handleClick">click</button>
    </h6>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

// i18nManager
import { useTestPackage } from 'test-ts-package'

export default defineComponent({
  name: 'PageIndex',
  setup () {
    const { hello } = useTestPackage()

    const handleClick = () => {
      console.log(hello.value)
      hello.value = 'lalal'
      console.log(hello.value)
    }

    return {
      hello,
      handleClick
    }
  }
})
</script>
```
And everything works as expected, Prints `Hello World` and when I click the button it changes to `lalal`

## Problem
Same thing in a Vue 2 + Composition API (Quasar) App

```vue
<template>
  <q-page class="row items-center justify-evenly">
    <h6 class="text-xl text-center text-gray-800">
      {{ hello }}
      <button @click="handleClick">click</button>
    </h6>
  </q-page>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api'

// i18nManager
import { useTestPackage } from 'test-ts-package'

export default defineComponent({
  name: 'PageIndex',
  setup () {
    const { hello } = useTestPackage()

    const handleClick = () => {
      console.log(hello.value)
      hello.value = 'lalal'
      console.log(hello.value)
    }

    return {
      hello,
      handleClick
    }
  }
})
</script>
```

Prints `hello world` and on button click I get the correct value in the console but not in the DOM and also if I import my package then all the reactive values stop working properly!

**Comment by kamnakis** [comment]
I figured it works fine in a Nuxt with Composition API project. Maybe there's something wrong with quasar projects? If I build my package with imports from @vue/composition-api then it works fine.

**Comment by antfu** [comment]
If it's not the problem of this project then I am going to close it for now. Please use Discord or Stackoverflow to ask questions. Thanks.

**Comment by kamnakis** [comment]
Seems like I was using composition api features before the Composition API plugin was installed! I left this here just in case someone does the same mistake!

**Comment by loilo** [comment]
Just a note for future visitors: I had the same issue (not with Quasar but with Gridsome) and the issue was that Gridsome and vue-demi used different versions of Vue. Gridsome used the `vue/dist/vue.runtime.common.js` while vue-demi used `vue/dist/vue.runtime.esm.js`. Using two different instances of `Vue` naturally will not work.

Forcing all parties to use the same Vue instance via a webpack alias did the trick for me:

```js
// This is not a full webpack configuration, just the part that's
// necessary for making vue-demi work with Gridsome
{
  resolve: {
    alias: {
      vue: require.resolve('vue/dist/vue.runtime.esm.js')
    }
  }
}
```
