### ISSUE TITLE
通过npm link方式调试的时候vue3出现警告，无法正常调试

### ISSUE THREAD

**Issue by 634323580** [vueuse/vue-demi#119]
**vue2**
正常

**"vue": "^3.2.13"**

`[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.`

无法正常调试，生命周期响应式等均无效果，发布到npm就没有这个问题。

**代码仓库:** https://github.com/634323580/lerma-frame/tree/master/packages/core

**Comment by SnowingFox** [comment]
我的建议是用英文写issue

**Comment by kakajun** [comment]
Maybe you can refer to this demo   https://github.com/kakajun/vue3-sketch-ruler,  use npx vue-demi-switch 3 to change vue-demi

**Comment by antfu** [comment]
`vue-demi` is not intended to be used with link. It's better to setup alias during developement.

**Comment by flyxiong819** [comment]
请问有解决了吗？我遇到了同样的问题

**Comment by flyxiong819** [comment]
how to setup alias to fix this problem?

**Comment by flyxiong819** [comment]
I use `yalc` to avoid this problem.
