### ISSUE TITLE
Object() is not a function 

### ISSUE THREAD

**Issue by shenjiuer** [vueuse/vue-demi#136]
当配置项目 webpack 的 externals 选项，将 vue 排除在 vendor 之外时， postinstall 执行会导致获取 vue 的版本出错，从而导致页面出现Object() is not a function 的问题
![image](https://user-images.githubusercontent.com/22869649/154731250-2d328e86-7c9f-4905-9485-788af45c2f9f.png)

**Comment by KesionX** [comment]
因为require加载之前vue可能还未加载，导致require错误。你可以使用vue-demi-fix修复

**Comment by shenjiuer** [comment]
> 因为require加载之前vue可能还未加载，导致require('vue')错误或获取到错误的vue版本。你可以使用vue-demi-fix修复

感谢

**Comment by luo10** [comment]
你好, 我也碰到了这个问题, 引入vue3使用没啥问题, 引入vue2就报错了.
![image](https://user-images.githubusercontent.com/17287671/157829517-a0bef66c-086c-437e-9ddb-427ccdcd3b37.png)
<img width="680" alt="image" src="https://user-images.githubusercontent.com/17287671/157829551-562245c4-10ef-420c-b9c3-2144d899e819.png">
编译的时候, 说找不到 vue.

我的vite.config.ts
```
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import Unocss from "unocss/vite";

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    lib: {
      entry: "./src/index.ts",
      name: "ApeBricks",
      fileName: (format) => `ape-bricks.${format}.js`,
    },
    rollupOptions: {
      external: ["vue", "lodash-es"],
      output: {
        globals: {
          vue: "Vue",
        },
      },
    },
  },
  optimizeDeps: {
    exclude: ["vue-demi"],
  },
  plugins: [vue()],
});

```
在vue2中 执行 npx vue-demi-fix 也没用.

**Comment by KesionX** [comment]
> 你好，我啥也报道了vue，引入了这个问题，引入vue2就错了。 的时候，找不到vue。 ![图片](https://user-images.githubusercontent.com/17287671/157829517-a0bef66c-086c-437e-9ddb-427ccdcd3b37.png) <img alt="图片" width="680" src="https://user-images.githubusercontent.com/17287671/157829551-562245c4-10ef-420c-b9c3-2144d899e819.png">
> 
> 我的vite.config.ts
> 
> ```
> import { defineConfig } from "vite";
> import vue from "@vitejs/plugin-vue";
> import Unocss from "unocss/vite";
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   build: {
>     lib: {
>       entry: "./src/index.ts",
>       name: "ApeBricks",
>       fileName: (format) => `ape-bricks.${format}.js`,
>     },
>     rollupOptions: {
>       external: ["vue", "lodash-es"],
>       output: {
>         globals: {
>           vue: "Vue",
>         },
>       },
>     },
>   },
>   optimizeDeps: {
>     exclude: ["vue-demi"],
>   },
>   plugins: [vue()],
> });
> ```
> 
> 在 vue2 中执行 npx vue-demi-fix 没有用。

hello，你可能可以尝试npx vue-demi-switch  2，如果还是不行的话，应该是软链接的问题，bin下的命令对应的vue-demi可能是另外一个包的，你得看下是否存在其他npm包引用了vue-demi

**Comment by luo10** [comment]
> hello，你可能可以尝试npx vue-demi-switch 2，如果还是不行的话，应该是软链接的问题，bin下的命令对应的vue-demi可能是另外一个包的，你得看下是否存在其他npm包引用了vue-demi

@KesionX hello, 我觉得可能是打包的问题?
https://github.com/luo10/vue-demi-test
我传了个简单的例子, vue3-components打包完, 在vue2-use中使用yalc引入, 就会出现vue找不到的问题, 但是在vue3-use中就不会出现....
能帮忙看看吗? 十分感谢.

**Comment by KesionX** [comment]
> yalc

hello，我测试了下，在我这是没问题的
![image](https://user-images.githubusercontent.com/15847900/158028135-6281e209-1747-4697-866b-b8e8db1d7c67.png)

vue找不到的问题，其中原因有可能是因为在install时vue-demi在postinstall阶段，项目内的vue并未加载完，而vue-demi已经加载完成。
如果你还是出现这个问题，一个简单的方法是你可以在项目外层npm i vue@2.x.x，在去vue2-use 下执行

**Comment by KesionX** [comment]
> > hello，你可能可以尝试npx vue-demi-switch 2，如果还是不行的话，应该是软链接的问题，bin下的命令对应的vue-demi可能是另外一个包的，你得看下是否存在其他npm包引用了vue-demi
> 
> @KesionX hello, 我觉得可能是打包的问题? https://github.com/luo10/vue-demi-test 我传了个简单的例子, vue3-components打包完, 在vue2-use中使用yalc引入, 就会出现vue找不到的问题, 但是在vue3-use中就不会出现.... 能帮忙看看吗? 十分感谢.

hello 我看了demo，因为你在 vue3-components 中devDependencies使用了"vue": "^3.2.25"，vue3-components打包出来的已经是vue3的了，自然在vue2-use无法使用。

**Comment by luo10** [comment]
> 

@KesionX  我查看了 vue-demi-switch 2 和 vue-demi-switch 3 不同状态打包出来的文件, 发现解析sfc模式的函数, vue2, vue3是不能兼容的... 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/17287671/158072514-2c37a4ed-c677-4754-82bc-7bf4c7623b02.png">
这些函数, 也不是 @vue/composition-api 能解决的...
要兼容的话得用h() 或者 jsx 去写模板文件..

**Comment by ChangerHe** [comment]
same question, createElementBlock and some other apis is declared in vue3. It's not exists in @vue/composition-api

**Comment by social-uni** [comment]
vue2 not running .  Object() is not function  ,vue2 not has cearetApp()

我是使用的是vue2版本， 可是vue-demi鉴定出来我的版本 是vue3   isVue2=false,isVue3=true, 这是错误的，我的版本是vue2

**Comment by xixiaocheng** [comment]
> Vue3 lib not working in Vue2 projects #152

我也遇到这样的问题。。。感觉是template的编译问题 如果这个很关键的痛点解决不了 那这个工具的意义何在啊

**Comment by sxzz** [comment]
let's track #152
