### ISSUE TITLE
Questions re: `script setup`; VTU

### ISSUE THREAD

**Issue by phobetron** [vueuse/vue-demi#137]
I have two questions that I haven't been able to gather from the documentation:

1. Are there any issues with `<script setup>` inside a library built on `vue-demi`? I assume it should be OK, since the `.vue` files are compiled to JS on build, as long as `vue-demi` can still get a handle on it.
2. Does the `vue-demi-switch` somehow support switching between `vue-test-utils` versions as well? The Vue 3-specific version of VTU has some breaking changes compared to the Vue 2 version.

**Comment by phobetron** [comment]
Closing to open a more clear issue.

**Comment by fidalgodev** [comment]
@phobetron were you able to use the `script setup` syntax, instead of importing `defineComponent` from `vue-demi`?

**Comment by phobetron** [comment]
@fidalgodev No, that isn't possible because the Vue2 compiler doesn't understand `<script setup>`. You can only use the options syntax, because it works (with some tweaks) for both compilers.
