### ISSUE TITLE
Module '"vue-demi"' has no exported member 'App'.

### ISSUE THREAD

**Issue by marekvospel** [vueuse/vue-demi#149]
I'm trying to create a vue plugin, and I decided to use rollup as my module bundler. My project is inspired by [pinia](https://github.com/vuejs/pinia), so it has similar dependencies, such as [`rollup-plugin-typescript2`](https://github.com/ezolenko/rollup-plugin-typescript2) to transpile the typescript, and to do type checks, but when enabling the `check` option, transpilation fails with the following message:
```
[!] (plugin rpt2) Error: <projectDir>/src/plugin.ts(1,15): semantic error TS2305: Module '"vue-demi"' has no exported member 'App'.
```
If the `check` option is disabled, the transpilation doesn't fail.

Here is a minimal repository, in which the error occurs
https://github.com/marekvospel/vue-demi-rollup

**Comment by marekvospel** [comment]
Seems to only be issue with pnpm

**Comment by marekvospel** [comment]
When going over [pinia](https://github.com/vuejs/pinia) once more, I noticed their `shamefully-hoist=true` option in their `.npmrc`.
With that option transpilation is successfull.

https://pnpm.io/npmrc#shamefully-hoist

**Comment by wobsoriano** [comment]
You added it only in the root file too?

**Comment by marekvospel** [comment]
Yes, the subprojects inherit the configuration from the root `.npmrc`
