### ISSUE TITLE
vue-demi adds @vue/composition-api to bundle, even if it is declared as external

### ISSUE THREAD

**Issue by johannes-z** [vueuse/vue-demi#151]
## Issue
My app breaks when adding any library that has `vue-demi` as a dependency, as it adds `@vue/composition-api` code to the final bundle, although I declared `@vue/composition-api` as external.

I resolve `@vue/composition-api` in an UMD/AMD environment automatically. Because there are two instances of `@vue/composition-api` present, the app breaks.

```ts
// relevant vite.config.ts

build: {
    rollupOptions: {
      external: [
        'vue',
        '@vue/composition-api'
      ],
    }
}
```

## Repro
* Create a vue 2 app,
* add `@vue/composition-api` and `@vueuse/core`
* import any function from e.g. `@vueuse/core`
* declare `@vue/composition-api` as external
* run npx vite build
* parts of `@vue/composition-api` end up in the bundle.

Also see this repro: https://github.com/johannes-z/vue-demi-repro. See https://github.com/johannes-z/vue-demi-repro/blob/main/dist/mylib.js#L1014

**Comment by johannes-z** [comment]
Using a regex for composition-api revealed the following:

```
// vite.config.ts
      external: id => {
        if (id === 'vue') return true
        return /\@vue\/composition-api/gi.test(id)
      },
```

results in

```js
define(["@vue/composition-api", "vue", "@vue/composition-api/dist/vue-composition-api.mjs"], factory)
```

and the following warning

> No name was provided for external module '@vue/composition-api/dist/vue-composition-api.mjs' in output.globals – guessing 'VueCompositionAPI'

**Comment by johannes-z** [comment]
I was able to find a temporary fix, by adding an alias:

```js
  resolve: {
    alias: [
      { find: '@vue/composition-api/dist/vue-composition-api.mjs', replacement: '@vue/composition-api' },
    ],
  },
```

**Comment by antfu** [comment]
```diff
external: [
   'vue',
   '@vue/composition-api',
+  'vue-demi'
]
```

And you should import everything from `vue-demi` instead of `vue` nor `@vue/composition-api`
