### ISSUE TITLE
<transition> tag not working

### ISSUE THREAD

**Issue by jens-morten-mikkelsen** [vueuse/vue-demi#164]
Hello 👋
First of all, loving vue-demi ❤
I am however, now running into an issue, where i cannot use <transition> in my vite/vue2 setup with tailwind.
im trying using the following:
```
<transition class="transition-opacity"
                enter="duration-300 ease-out"
                leave="duration-200 ease-in"
                enter-from="opacity-0 -translate-x-full"
                enter-to="opacity-100 translate-x-0"
                leave-from="opacity-100 translate-x-0"
                leave-to="opacity-0 -translate-x-full">
    <div v-if="open">
        <p>fade in from right</p>
    </div>
</transition>
```

But im not seeing any of the transitionary classes or style going on in the DOM.
Anybody have any suggestions? :)

**Comment by antfu** [comment]
I don't think it's related to this project. Please use forum of discord to ask questions.
