### ISSUE TITLE
Can't import the named export 'isVue2' from non EcmaScript module

### ISSUE THREAD

**Issue by taidaid** [vueuse/vue-demi#171]
Hello, I understand that this may not be exactly the right place for this question, but it seems related to `vue-demi`, so I thought people here might be able to help.

This is a repost from [this issue thread](https://github.com/vuejs/pinia/issues/675#issuecomment-1172149485).

Thanks for taking a look.
 
---
Hello, we are trying to use Pinia alongside Vuex in a Nuxt 2 project in order to smooth our eventual migration to Nuxt 3. However, even after adding
```
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
```
to our build config, we are still seeing the `Can't import the named export 'isVue2' from non EcmaScript module (only default export is available)`. The error comes from our ./.nuxt/dist.plugin.209980bd.mjs file which seems to be the @pinia/nuxt plugin setup.

Here is some of our package.json
```
// dependencies
"nuxt": "2.15.8",
"vue": "2.6.14",
"@nuxtjs/composition-api": "^0.23.2" ,
"@pinia/nuxt": "^0.1.9",
"pinia": "^2.0.14

// devDependencies
"@nuxt/typescript-build": "2.1.0"
```
We tried some experiments such as deleting the `.cjs` file from `vue-demi`, but it seems that no matter what we do, the file is not reading the `.mjs` file correctly.

**Comment by knirirr** [comment]
@taidaid may I ask what your solution to this was? Unfortunately, I've run into the same problem (same scenario as you). Thanks!

Edit: 

In case anyone else finds this, what eventually fixed it for me was this:

```
 {
          test: /\.mjs$/,
          include: [/node_modules/, /.nuxt/],
          type: "javascript/auto"
},
```
