### ISSUE TITLE
resolveComponent is not supported in vue 2

### ISSUE THREAD

**Issue by ibustosca** [vueuse/vue-demi#181]
I have this code in my library project with vue 3:

`<script lang="ts">
import { h, defineComponent, resolveComponent } from 'vue-demi'

export default defineComponent ({
  name: 'ivan-button',
  data() {
    return {
      msg: 'hello'
    }
  },
  render() {
    const oButton = resolveComponent('o-button')
    return h(oButton, { variant: 'success', size: 'small', label: this.msg, rounded: true })
  }
})
</script>`

And, when I import my library in my vue 2 project, I have the following error:

`"export 'resolveComponent' (imported as 't') was not found in 'vue-demi'`

Any idea?

Regards y thanks.

**Comment by antfu** [comment]
`vue-demi` only makes the alias between different versions of Vue. This is out-of-scope. You might want to send request to Vue 2 instead.

**Comment by akhma-ps** [comment]
@ibustosca I think in the vue2 case you can use the string name of the component. But for `resolveComponent` you still have to use a workaround:

```
import {
  getCurrentInstance,
  isVue2,
} from 'vue-demi';

render() {
  const OButton = isVue2 ? 'o-button' : getCurrentInstance().appContext.components.OButton;

  return h(OButton, ...);
}
```
