### ISSUE TITLE
vue3版本下开发的组件 无法在vue2环境使用

### ISSUE THREAD

**Issue by xixiaocheng** [vueuse/vue-demi#188]
![1091661093614_ pic](https://user-images.githubusercontent.com/29592694/185797134-66324d5e-971d-4562-b06d-17e5a07d6e74.jpg)
应该是template的原因，所以是是只能jsx或者render？

**Comment by sakibcc** [comment]
这里是因为你使用了vue3的sfc-compiler去构建，然后项目是vue2时，vue2并没有对应的function

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/29446569/185887476-5acc4a8b-4a3b-4641-b496-6025e601d1f0.png">

可以参考一下我的这个项目，是基于@vitejs/plugin-vue的自定义compiler，在同一个项目同时打包vue2和vue3版本的组件
https://github.com/sakibcc/vue-demi-sfc-component
