### ISSUE TITLE
There is a problem with the vue-demi 0.13.10 version in the nuxt2 project, and the warn method in the production environment cannot be found

### ISSUE THREAD

**Issue by SGAMERyu** [vueuse/vue-demi#191]
![image](https://user-images.githubusercontent.com/17926105/186389460-58889238-7337-4826-a3b5-a182169cd184.png)
The util method in the variable r is in the default field, but it is not exported
![image](https://user-images.githubusercontent.com/17926105/186390508-17d0268c-8cda-46e8-9bde-176f2825b3d4.png)

**Comment by posva** [comment]
Duplicate of #192
