### ISSUE TITLE
Should not use vue inner util, after upgrade everything doesn't worked

### ISSUE THREAD

**Issue by lijing666** [vueuse/vue-demi#192]
latest version of vue-demi added  `var warn = Vue.util.warn` cause all old webpack build doesn't worked 
``` js
import Vue from 'vue'

var isVue2 = true
var isVue3 = false
var Vue2 = Vue
var warn = Vue.util.warn
```
this error is Vue.util is undefined

**Comment by zbjcool** [comment]
![image](https://user-images.githubusercontent.com/1535811/186560194-f8694cf0-a6c7-49b5-b1be-bb9c224b2c8f.png)
It happened to me too

**Comment by lijing666** [comment]
> ![image](https://user-images.githubusercontent.com/1535811/186560194-f8694cf0-a6c7-49b5-b1be-bb9c224b2c8f.png) It happened to me too

The problem is because old webpack `var Vue = require('vue')` is not `Vue.default` but Vue itself ，so Vue.util is undefined and Vue.default.util is defined

**Comment by cyaque** [comment]
Same for me, crashed a release of a nuxt 2 project on my side.

**Comment by posva** [comment]
Does anybody has a boiled down repro? I don't see why `Vue.util` wouldn't work while `Vue.config` does

In https://github.com/posva/old-cli-vue-router it uses the esm version and it works fine

**Comment by cyaque** [comment]
It is not vue.util, it is vue.warn that crashes. Im in the middle of 4 releases, and patching this projects through, so I can't do much right now sorry.

**Comment by posva** [comment]
It's `Vue.util.warn` and fails at `Vue.util`. The screenshots suggest it should be `Vue.default.util.warn` but then everything also in this file also needs to be changed. I will take a look once it can be reproduced. I couldn't reproduce on a nuxt 2 project either: https://github.com/piniajs/example-nuxt-2

**Comment by cyaque** [comment]
Apologies, didn't check carefully. I've solved it by forcing a specific version (downgrade to 13.8).

I'm sharing my package json, may be it may help for the repro steps:

`"dependencies": {
    "@nuxt/config": "^2.15.8",
    "@nuxt/types": "^2.15.8",
    "@nuxt/typescript": "2.7.1",
    "@nuxt/typescript-runtime": "^2.1.0",
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/cloudinary": "^1.0.3",
    "@nuxtjs/composition-api": "^0.32.0",
    "@nuxtjs/dotenv": "^1.4.1",
    "@nuxtjs/eslint-config": "0.0.1",
    "@nuxtjs/strapi": "^0.3.4",
    "@pinia/nuxt": "^0.1.9",
    "@types/jest": "24.0.13",
    "@typescript-eslint/eslint-plugin": "1.9.0",
    "core-js": "^3.15.1",
    "lodash": "^4.17.21",
    "nuxt": "^2.15.7",
    "nuxt-clipboard": "^0.0.6",
    "nuxt-property-decorator": "^2.9.1",
    "pinia": "^2.0.14",
    "ts-loader": "^8.2.0",
    "typescript": "^4.5.4",
    "vue-demi": "0.13.8",
    "vue-json-excel": "^0.3.0",
    "vue-lodash": "^2.1.2"
  },
  "devDependencies": {
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/svg": "^0.2.0",
    "@nuxtjs/tailwindcss": "^4.2.0",
    "@tailwindcss/forms": "^0.5.1",
    "node-sass": "^4.13.1",
    "postcss": "^8.3.5",
    "sass-loader": "^10.1.1",
    "tailwindcss": "^2.1.1"
  }`

**Comment by sctouch** [comment]
Yes, the same issue on `0.13.9` or `0.13.10`. after nuxt generate.

**Comment by sctouch** [comment]
> It's `Vue.util.warn` and fails at `Vue.util`. The screenshots suggest it should be `Vue.default.util.warn` but then everything also in this file also needs to be changed. I will take a look once it can be reproduced. I couldn't reproduce on a nuxt 2 project either: https://github.com/piniajs/example-nuxt-2

@posva you have build or generate the project, next you have to start the project in your local `yarn start` and you will see the error.
