### ISSUE TITLE
"export 'defineComponent' was not found in 'vue-demi'

### ISSUE THREAD

**Issue by Z-Champion** [vueuse/vue-demi#207]
使用 @antv/x6-vue-shape 包时，出现以下问题：
使用npm本地启动项目时，控制台出现：
![image](https://user-images.githubusercontent.com/33289026/212839799-a3e1d2c0-0a52-48f1-be44-5e9906ec3d53.png)
打开设计器页面出现以下问题：
![image](https://user-images.githubusercontent.com/33289026/212839931-cc944382-5a99-4adc-8f08-2b495dcc7193.png)
尝试过使用 vue-demi-fix 以及 vue-demi-switch 2 都没有解决。

**Comment by xxumeng** [comment]
> 使用 @antv/x6-vue-shape 包时，出现以下问题： 使用npm本地启动项目时，控制台出现： ![image](https://user-images.githubusercontent.com/33289026/212839799-a3e1d2c0-0a52-48f1-be44-5e9906ec3d53.png) 打开设计器页面出现以下问题： ![image](https://user-images.githubusercontent.com/33289026/212839931-cc944382-5a99-4adc-8f08-2b495dcc7193.png) 尝试过使用 vue-demi-fix 以及 vue-demi-switch 2 都没有解决。

哈喽~这个问题后来是怎么解决的呢？我们也遇到了相同的问题

**Comment by beautiful-night** [comment]
npm i --ignore-scripts，忽略脚本的时候，安装的vue-demi里面 isVue3 = true
<img width="788" alt="image" src="https://github.com/user-attachments/assets/086362b4-984b-45fb-8e7c-78a69eabdb86" />
