### ISSUE TITLE
CDN error: @vue/composition-api before vue-demi

### ISSUE THREAD

**Issue by luizfeer** [vueuse/vue-demi#208]
i using CDN in my page:
```
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
<script src="https://unpkg.com/vue-demi@0.12.1/lib/index.iife.js"></script>
<script src="https://unpkg.com/vue-recaptcha@1.3.0/dist/vue-recaptcha.min.js"></script>
```

but:
[vue-demi] no VueCompositionAPI instance found, please be sure to import `@vue/composition-api` before `vue-demi`.
![image](https://user-images.githubusercontent.com/3594167/213472240-1b24980d-42b7-4c55-9961-e42df5795835.png)

**Comment by LockingReal** [comment]
> i using CDN in my page:
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
> <script src="https://unpkg.com/vue-demi@0.12.1/lib/index.iife.js"></script>
> <script src="https://unpkg.com/vue-recaptcha@1.3.0/dist/vue-recaptcha.min.js"></script>
> ```
> 
> but: [vue-demi] no VueCompositionAPI instance found, please be sure to import `@vue/composition-api` before `vue-demi`. ![image](https://user-images.githubusercontent.com/3594167/213472240-1b24980d-42b7-4c55-9961-e42df5795835.png)

I think this answer may be useful to you ~🤓

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Answer</title>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
    <script src="https://cdn.jsdelivr.net/npm/@vue/composition-api@1.7.1"></script>
    <script src="https://unpkg.com/vue-demi@0.12.1/lib/index.iife.js"></script>
    <script src="https://unpkg.com/vue-recaptcha@1.3.0/dist/vue-recaptcha.min.js"></script>
    <script>
        // Try to use cdn to pull [composition-api] resources before [vue-demi]
        console.log(window.VueDemi);
    </script>
</body>
</html>
````
