### ISSUE TITLE
Import error using with reactivue.

### ISSUE THREAD

**Issue by Dav3rs** [vueuse/vue-demi#21]
I'm trying to use vueuse with reactivue and I'm getting this error:

![imagen](https://user-images.githubusercontent.com/50024128/100020137-51ce5180-2dad-11eb-9a7e-a430ff13ae37.png)

**Comment by Dav3rs** [comment]
With Vue3 that part of the compilation seems to continue fine, but then the code starts to break in places that previously compiled without problem. If I fill the file with //@ ts-ignore it compiles ok, but then one file after another gets broken types too, files that have nothing to do with it.

![imagen](https://user-images.githubusercontent.com/50024128/100047452-84457200-2de0-11eb-924a-4e85fdc1e417.png)

![imagen](https://user-images.githubusercontent.com/50024128/100102174-39a01600-2e31-11eb-8adb-c547e6b9c30e.png)

Just by removing the import from @vueuse/core everything compiles without type problems, I'm sure this doesn't happen in plain javascript, it's something with typescript that goes crazy in the whole project.

I will try later to test this in a clean proyect.

**Comment by antfu** [comment]
Is that still a case?

**Comment by antfu** [comment]
Close for now. Feel free to reopen with a proper reproduction if it still occurs.
