### ISSUE TITLE
Pinia2.1.3 + vue3.3.4 does not work: hasInjectionContext is not defined

### ISSUE THREAD

**Issue by qq958691165** [vueuse/vue-demi#233]
pinia.mjs:6  Uncaught SyntaxError: The requested module '/node_modules/vue-demi/lib/index.mjs?v=151548d1' does not provide an export named 'hasInjectionContext' (at pinia.mjs:6:10)

**Comment by lixin59** [comment]
I had the same problem
![image](https://github.com/vueuse/vue-demi/assets/57742124/35ea8962-2edf-485f-afdf-6d38b4cf2cdb)
![image](https://github.com/vueuse/vue-demi/assets/57742124/ed86f0b0-a4f2-485f-8628-16b50a9644f4)
![image](https://github.com/vueuse/vue-demi/assets/57742124/f19a114b-8b6f-4ce2-8bd7-8e5fc902827b)

**Comment by Teaghy** [comment]
> 我有同样的问题 ![图像](https://user-images.githubusercontent.com/57742124/239475648-35ea8962-2edf-485f-afdf-6d38b4cf2cdb.png) ![图像](https://user-images.githubusercontent.com/57742124/239475754-ed86f0b0-a4f2-485f-8628-16b50a9644f4.png) ![图像](https://user-images.githubusercontent.com/57742124/239475283-f19a114b-8b6f-4ce2-8bd7-8e5fc902827b.png)


This is because your vite-plugin-uni plugin is based on [vue@3.2.47](mailto:vue@3.2.47). hasInjectionContext is a method added in version 3.3, which Pinia is currently using and requires the latest 3.3 version. If you are using Vue 3.2, you cannot use the latest version of Pinia.

**Comment by LuckyArd110** [comment]
I'm sure this happens to programmers all over the world

**Comment by RSS1102** [comment]
> 

yes.`pinia` the new version should be with ` Vue@3.3` +.

**Comment by RSS1102** [comment]
yes, thanks.I also encountered this problem.
`pinia` the new version should be with ` Vue@3.3` +.

---

@posva should this indicate a warning in Pinia's docs?

**Comment by posva** [comment]
This error means you dont have the necessary vue version installed. Pinia has the peer dependency set to ^3.3.0, it’s important to not ignore that warning when installing.

If a library like uview plus is adding vue as a dependency, it can also create this kind of errors, but that an issue to be reported there

You can use pnpm why vue to check the installed version and debug further but this goes beyond vue-demi’s responsibility
