### ISSUE TITLE
v0.14.5 recently overwritten? and v0.14.6 does not work...

### ISSUE THREAD

**Issue by ESP-Marc** [vueuse/vue-demi#244]
In relation to tickets:

https://github.com/vueuse/vue-demi/issues/242
https://github.com/vueuse/vue-demi/issues/230

I have noticed that the file content of `v0.14.5` has greatly changed (content overwritten?) but I do not know when this happened.

All I know is this:  The 3rd of September is the last time I last ran a `yarn install` and my project builds fine and does not experience the issue outlined in #230

However, a college pulled our current commit that works for me right now and ran yarn install today (7th September) and noted our project does not work, reporting same issue #230.

So I pull a fresh new copy in a new directory on my system and run yarn install in there and indeed was now experiencing the same #230 issue my colleague reported.

So here I am, 2 copies of the same project on the same commit hash, one works one doesn't...
**Why?** well when I did an IDE compare with directory of this library (/node-modules/vue-demi) on both projects both running version `0.14.5`, the diff is big.

See my attached screenshot showing the diff between an old pull of `0.14.5` (10/06/2023) and a recent pull of the same version (07/09/2023).

I think an NPM publish was done at some point in the last few months, most likely this week, where unfinished changes intended for v0.14.6 got re-published to 0.14.5 despite the NPM distribution site saying the version was Published 4 months ago?

![Screenshot 2023-09-07 175842](https://github.com/vueuse/vue-demi/assets/116962814/043be160-a6be-423d-b7fe-20b46f56ff1f)

**Comment by antfu** [comment]
```bash
npx npm-diff vue-demi 0.14.4 0.14.5

npx npm-diff vue-demi 0.14.5 0.14.6
```

There do not seem to be many changes between those versions on npm (align with the commit history and nothing strange to me).

Just note that `vue-demi` works by swapping the files based on your Vue version, so I assume it's something changed in your environment rather than vue-demi itself.

I would need a minimal reproduction to prove it's vue-demi's issue.

**Comment by antfu** [comment]
I'll need to control the variables and narrow them down to the root cause. If there isn't a massive change in vue-demi's npm dist, then it must be something else causing that. I can't help as I don't have a reproduction on my end.

**Comment by posva** [comment]
A reproduction is a repository where the installation of vue-demi fails, not the vue-demi downloaded packages.

Note you can force the version of Vue as noted in the readme

**Comment by posva** [comment]
Can you make the repro minimal [it has too many things that are unrelated](https://github.com/ESP-Marc/demi-6-pinia/blob/main/package.json#L12-L46). Should probably only have vue, pinia and the CLI service

**Comment by posva** [comment]
Alright, so it was about the post-install script after all 😄
