### ISSUE TITLE
vue-demi-fix is missing

### ISSUE THREAD

**Issue by aghArdeshir** [vueuse/vue-demi#246]
Hi. In the README.md, there is a section that says if postinstall is missed, you can run `npx vue-demi-fix` 

but I can't, and it fails:
![image](https://github.com/vueuse/vue-demi/assets/5755214/a8976163-fc09-498d-97d5-0741cee6ce30)

**Comment by antfu** [comment]
You need to install `vue-demi` first.

**Comment by aghArdeshir** [comment]
Oops, thanks :heart:

**Comment by thedamon** [comment]
Interesting. Just ran into this. I think it's confusing as typically npx will run fine if you don't have the package installed.

**Comment by aghArdeshir** [comment]
And I also have another question, can't someone suspicious just go ahead and publish a package to `npm` called `vue-demi-fix`? https://www.npmjs.com/package/vue-demi-fix

I suggest you (the vueuse team) create and publish a package called `vue-demi-fix` which all it does is informing people about the usage.

That's exactly what browserslist does, if instead of
```
npx browserslist@latest --update-db
```

you do (notice the typo)
```
npx browserlist@latest --update-db
```

all you see is a package that says "you made a typo". And that package (browserlist) is also published by the tool author itself.

**Comment by aghArdeshir** [comment]
![image](https://github.com/vueuse/vue-demi/assets/5755214/c9c089d0-7b02-4539-8d42-2ac2aa86d774)
