### ISSUE TITLE
vue-demi does not list @vue/composition-api as a dependency

### ISSUE THREAD

**Issue by Demivan** [vueuse/vue-demi#29]
When using `pnpm` (hoist = false) or `yarn@berry` webpack build fails as `vue-demi` tries to access `@vue/composition-api` without listing it as a dependency.
It is the same issue as #9 but for `@vue/composition-api`. Why was is removed from peer dependencies?

**Comment by antfu** [comment]
I was removed because of #15 and now I am confused about how to make it work for both npm and yarn... Any suggestions?

**Comment by Demivan** [comment]
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta can be used to specify optional peer dependencies. If npm v7 does not install optional peer dependencies it should be correct solution.

**Comment by antfu** [comment]
I have added a test script to enum every package manager in #30 but can't repro the problem you are facing. Can you give it a look and see if I have missed anything? (A PR to make yarn berry fails would be greatly appreciated!) Thanks.

**Comment by Demivan** [comment]
Will try to reproduce tomorrow. I was not able to reproduce it on smaller project.
Tests need to be adjusted for yarn@berry. Looks like it is not using berry version at all. Maybe need to call `yarn set version berry` in test project.
These lines should not work:
https://github.com/antfu/vue-demi/blob/564197f23feff2d058d56b80c9798ac72f5f75dd/.github/test.js#L20
https://github.com/antfu/vue-demi/blob/564197f23feff2d058d56b80c9798ac72f5f75dd/.github/test.js#L27
There is no `node_modules` folder and to call scripts you need to use `yarn node` instead of `node`

**Comment by Demivan** [comment]
After some investigation I was able to reproduce this: https://github.com/Demivan/vue-demi-test

To reproduce with pnpm:
- checkout `pnpm` branch
- `pnpm i`
- `pnpm test`

Fixed version:
- checkout previous commit or uncomment line in pnpmfile.js
- `rm pnpm-lock.yaml`
- `pnpm i`
- `pnpm test`

To reproduce with yarn:
- checkout `yarn` branch
- `yarn`
- `yarn test`

Fixed version:
- checkout previous commit or uncomment lines in .yarnrc.yml
- `yarn`
- `yarn test`

I was not able to reproduce for simpler project because of this https://pnpm.js.org/en/faq#solution-1. Both `pnpm` and `yarn@berry` allow packages to access dependencies defined in root project package.json as a fallback.

**Comment by antfu** [comment]
Thanks for the repro! I'd like to take this chance to setup the test for each agents and your test repo would definitely help. Will get you back after I have set them up.

**Comment by Demivan** [comment]
I'm going to close this. https://github.com/vueuse/vue-demi/commit/559eec61c2ab5d5f2676edfed014f0d9effaee67 fixed this issue.
