### ISSUE TITLE
vue-demi doesn't include Plugin export

### ISSUE THREAD

**Issue by gregveres** [vueuse/vue-demi#32]
vuelidate is using vue-demi to help them with their new version support both Vue 2 and Vue 3. They need access to the equivalent of the Plugin. This is a new type in Vue 3 and should have an equivalent in Vue 2. 

Is there a way that Vue-demi could provide a common abstraction? 
Here is the open in issue on vuelidate
https://github.com/vuelidate/vuelidate/issues/767

**Comment by antfu** [comment]
If the types are defined in `@vue/composition-api` but not exported, you can make a PR to it so `vue-demi` could have them automatically. For those are not applicable in `@vue/composition-api`, I am happy to have them in https://github.com/vueuse/vue-demi/blob/master/lib/v2/index.d.ts

**Comment by gregveres** [comment]
I would be happy to help, but I don't know what type a "Plugin" is for Vue 2. The Plugin type seems to be new for Vue 3, but it definitely exists in Vue 2 since plugins are not new.

This is outside of the composition api. It is something that would go into the index.d.ts I think.
I was thinking that if Plugin was defined as an alias to the appropriate type in Vue 2 that would work. That way a user of vue-demi could refer to plugin going forward and vue-demi would map it to the appropriate Vue 2 type. 

Does that make sense?

**Comment by antfu** [comment]
Sounds good, let's see the PR, thanks!
