### ISSUE TITLE
vue-demi breaks composition-api template re-rendering (vue2)

### ISSUE THREAD

**Issue by lstoeferle** [vueuse/vue-demi#35]
Hello @antfu ,

I am currently working on a SPA using `vue2` + `options-api` .  This SPA imports another component library (`vue2` + `@vue/composition-api`), which simply exposes a single vue component. The component library also uses `@vueuse/core` using `vue-demi`.

Here's an example of the exported component of the library (can not share everything since it's an company internal project)
```vue
<template>
  <div>
    <p>FOO: {{ blub }}</p> <!-- will stay false -->
    <button @click.stop="click">CLICK ME</button>
  </div>
</template>

<script>
import { defineComponent, ref } from "@vue/composition-api"
import { useLocalStorage } from "@vueuse/core"

export default defineComponent({
  setup: (props) => {
    const foo = ref(false)

    const storageLocale = useLocalStorage("some_key", "en-GB", {
    listenToStorageChanges: true,
      window,
    })

    return {
      foo,
      click: () => {
        console.log("before click", foo.value)
        foo.value = true
        console.log("after click", foo.value) // <-- will be true
      },
    }
  },
})
</script>
```

So basically everything works pretty good. But as soon as I add the `useLocalStorage`  or any other composable from `@vueuse/core`, the template will not re-render as soon as the button was clicked. The ref value itself works, only the template does not update. I did a lot of debugging together with my colleague, and we figured out that the template will update, as soon as we get rid of all `vue-demi` based code.

Dependencies of the SPA:
```json
"dependencies": {
    "vue": "^2.6.10",
    "@company/components": "1.0.0",
    "@vue/composition-api": "1.0.0-beta.25"
},
"devDependencies": {
  ... all other
}
``` 
Dependencies of the ComponentLibrary: 
```json
"dependencies": {
   "@vueuse/core": "4.0.10"
},
"devDependencies": {
  "vue": "^2.6.10",
  "@vue/composition-api": "1.0.0-beta.25"
  ... all other
}
```

Do you know what could be the issue here?

Kind regards,
Lukas

**Comment by noook** [comment]
Did you check the devtools, see if the state updated ? The state will probably display the `.value` key of your `useLocalStorage`.

It might be related to https://github.com/vuejs/composition-api/issues/587 : You'll need to externalize the composition api and vue dependency from your lib build

**Comment by lstoeferle** [comment]
Hi @noook , thanks for the hint. Externalizing the dependencies from lib build did not work.

We figured out, that the issue only appears when the lib project is linked locally to the SPA project via
```sh
npm link ~/path/to/the/lib
```

While using the package from the npm repository, everything works fine.

**Comment by noook** [comment]
To prevent this kind of issue, you can remove packages `vue` and `@vue/composition-api` from the lib's `node_modules`. It will prevent the app from using two different instances of the composition API package.

**Comment by antfu** [comment]
@lstoeferle 

Your snippet shows you are importing from `@vue/composition-api` instead of `vue-demi`, not sure if it's the problem.

Can you also check the dist file to see if it bundles the code from `@vue/composition-api`? Thanks.

**Comment by lstoeferle** [comment]
Removing the packages `vue` and `@vue/vue-composition-api` resolved the issue 👍. Thanks for your help 👏
