### ISSUE TITLE
[Discussion] Shall we add something like `Vue2` to vue-demi's export?

### ISSUE THREAD

**Issue by Justineo** [vueuse/vue-demi#41]
My use case is to config `ignoredElements` only in Vue 2. Currently we may use:

```ts
import { Vue, isVue2 } from 'vue-demi'

if (isVue2) {
  Vue.config.ignoredElements.push(...)
}
```

The problem is that when this code is run with Vue 3, `Vue` contains all tree-shakable exports which is not ideal.

So shall we add a `Vue2` export from vue-demi so that we can use it like:

```ts
import { Vue2 } from 'vue-demi'

if (Vue2) {
  Vue2.config.ignoredElements.push(...)
}
```

And in Vue 3 mode we just export `undefined` from `vue-demi` so it doesn't hurt the bundle size.

**Comment by antfu** [comment]
Sounds like a good solution to me. Would you like to make a PR for it? I think we can mark the `Vue` entry as `@depreacted` so it won't break the existing code but also give clear info for developers to migrate. Thanks.

**Comment by Justineo** [comment]
Sure.
