### ISSUE TITLE
Supporting non Vue project ? (via @vue/reactivity ?)

### ISSUE THREAD

**Issue by Benoit-Vasseur** [vueuse/vue-demi#48]
Hello,

I am building a library that uses @vue/reactivity to have some reactive data (no Vue components).
The library may be used by a Vue project but also React, Angular, whatever ....

Does vue-demi can help for this "support" ?

Today it seems that is it Vue centric (Vue 2 or 3). Can it make sense to support @vue/reactivity to extends the "universal aspect" ?

**Comment by antfu** [comment]
For now, you can ask users to run 

```ts
npx vue-demi-switch 3 @vue/reactivity
```

to re-target vue-demi to `@vue/reactivity`. I will add a feature to read configurations making this process automatic. Contributions are also welcome.

**Comment by Benoit-Vasseur** [comment]
Thanks for your quick reply and I am glad that there is already a way to support @vue/reactivity.

I will do some tests to be sure that I "need" vue-demi to allow every users to use my library. I just tested my lib (which use @vue/reactivity but not bundled in the lib) in a Vue3 project (via Vite) and it seems to work fine. I will test it in a React project and a vue-cli project (webpack) and see how it behaves.

I may contribute to vue-demi, depending to those tests ;).
