### ISSUE TITLE
How to do Vue.use(CompositionAPI) in tests?

### ISSUE THREAD

**Issue by MartinMalinda** [vueuse/vue-demi#5]
Hey, first of all great library it's something that's been much needed 👍 so thanks a bunch

I tried to use it in https://github.com/MartinMalinda/vue-concurrency and I hit a blocker that it breaks my test suite.

I have a quick setup file that is being run before every test:

https://github.com/MartinMalinda/vue-concurrency/blob/master/test-utils/vue-setup.ts

This worked fine before but it doesn't do the trick now when I import from `vue-demi`. I guess I do `.use` on wrong `Vue`. Perhaps there needs to be `import { Vue } from 'vue-demi';`  solely for testing purposes?

**Comment by MartinMalinda** [comment]
Huh, there is a Vue exported, so I'm trying:

```ts
import Vue from "vue";
import CompositionApi from "@vue/composition-api";
import { Vue as VueDemiVue } from 'vue-demi';

Vue.use(CompositionApi);
VueDemiVue.use(CompositionApi);
```

But I get:

```
TypeError: Cannot read property 'use' of undefined
```

**Comment by antfu** [comment]
Thanks, I will have a look at that.

And you don't have to install VCA I think. vue-demi should already do that for you. 

Meanwhile, If you want to install other plugins, the best way to do might be: 
```ts
import { createApp } from 'vue-demi'

const app = createApp()
app.use(xxxx)
```

as `Vue.use` is no longer there in Vue 3. `createApp` in Vue 2 is a polyfill by VCA plugin and it's equivalent to `Vue.use`.

**Comment by MartinMalinda** [comment]
I'm doing now `import Vue from "vue-demi";` in tests

Then I'm creating a wrapper component in which I want to test the utility functions

```ts
export function createComponentStub(
  name: string,
  setup = (props, context) => { }
) {
  const stubAttr = `data-test-${name}-stub`;
  return Vue.defineComponent({
    name,
    setup,
    render(el) {
      return el("div", {
        attrs: {
          [stubAttr]: true,
        },
      });
    },
  });
}
```

When I render this component I pass localVue from `vue-demi`:

```ts
 render(component, {
    localVue: Vue as any
  });
```

Still it seems that `setup()` does not get called, which is strange because the imported Vue AFAIK should have the compositionAPI plugin added: 

https://github.com/antfu/vue-demi/blob/master/lib/v2/index.esm.js#L5

**Comment by MartinMalinda** [comment]
But

`console.log(Vue['__composition_api_installed__']);` seems to print false, so maybe it's not the case

**Comment by MartinMalinda** [comment]
If I uninstall VCA completely I'm getting:

```
Test suite failed to run

    Cannot find module '@vue/composition-api' from 'node_modules/vue-demi/
lib/v2/index.cjs.js'

    Require stack:
      node_modules/vue-demi/lib/v2/index.cjs.js
      node_modules/vue-demi/lib/index.cjs.js
      test-utils/vue-setup.ts
```

**Comment by antfu** [comment]
Yes. From v0.3.x, `@vue/composition-api` becomes a peerDependency which you should install it manually.

**Comment by antfu** [comment]
And I think you should use 
```ts
import { defineComponent } from "vue-demi"
```

instead of 
```ts
import Vue from "vue-demi"
```

**Comment by Devoter** [comment]
> But
> 
> `console.log(Vue['__composition_api_installed__']);` seems to print false, so maybe it's not the case

Yes, that looks strange:

```ts
import VueCompositionApi from '@vue/composition-api';
import { Vue, isVue2, createApp, defineComponent, isVue3 } from 'vue-demi';

import { tracked, calculated } from '.';

if (isVue2) {
  console.log('Vue 2', ((Vue as unknown) as Record<string, unknown>)['__composition_api_installed__']); // Vue 2 undefined ?!
  Vue.use(VueCompositionApi);
  console.log('Vue 2', ((Vue as unknown) as Record<string, unknown>)['__composition_api_installed__']); // Vue 2 true
}
```

**Comment by antfu** [comment]
@Devoter What is the bundler you are using? Can you share a reproduce repo? Thanks.

**Comment by Devoter** [comment]
@antfu Sorry, I cannot share a repo for now. I use bili for building and ts-jest for testing. I'll try to prepare it for you later.

**Comment by MartinMalinda** [comment]
Minimal repro: https://github.com/MartinMalinda/vue-tiny-emitter

**Comment by antfu** [comment]
@MartinMalinda Sorry for the delay but I just pull done your repo and it seems to work for me

![image](https://user-images.githubusercontent.com/11247099/97419873-9220e800-1945-11eb-8056-49e7a793bb5c.png)

**Comment by Devoter** [comment]
> @MartinMalinda Sorry for the delay but I just pull done your repo and it seems to work for me
> 
> ![image](https://user-images.githubusercontent.com/11247099/97419873-9220e800-1945-11eb-8056-49e7a793bb5c.png)

I have to confirm, everything works fine with the lastest version. I don't know why.
