### ISSUE TITLE
Change char direction

### ISSUE THREAD

**Issue by udicol** [vueuse/vue-demi#52]
Hi,
I'll be glad to change direction of text to "RTL" for hebrew language.
Best

**Comment by antfu** [comment]
Sorry, what do you mean?

**Comment by udicol** [comment]
Hi,
Just to let us read hebrew language char direction from ltr to rtl (Right to left)
Thanks

**Comment by lstoeferle** [comment]
Do you mean that you want a function, which reverses a text from LTR to RTL?
