### ISSUE TITLE
onMounted is not work in vitepress

### ISSUE THREAD

**Issue by aloha66** [vueuse/vue-demi#55]
Hi,I found some issues when I implement vue-demi in vitepress,but switching to vue  it is ok,such as onMounted,reactivy data lose.Reactivy data lose  hard to repo,so here is a [onMounted  repo](https://github.com/aloha66/vitepress-repo)
```vue
<script setup lang="ts">
import { onMounted } from "vue-demi"; // in vite,cli is ok ,not work in vitepress
// import { onMounted } from "vue"; // ok

onMounted(() => {
  console.log("onMounted");
});
</script>
```

**Comment by antfu** [comment]
Have you tried this?
https://github.com/vueuse/vueuse/blob/8e042923270462679c88a1517a655ca7001ce118/packages/vite.config.ts#L18-L20

**Comment by aloha66** [comment]
Great,thanks
