### ISSUE TITLE
vue-demi fails getting 'markReactive' from latest @vue/composition-api

### ISSUE THREAD

**Issue by tbtalbottjr** [vueuse/vue-demi#56]
I am trying to use **vue-echarts 6.0.0-rc4**, which uses **vue-demi 0.7.5**.
vue-echarts requires installing @vue/composition-api for Vue2 support.

With **@vue/composition-api 1.0.0-rc7**, I get:
```
ERROR in ./node_modules/vue-demi/lib/index.esm.js 18:0-488
"export 'markReactive' was not found in '@vue/composition-api'
```

I have to back all the way down to **@vue/composition-api 1.0.0-beta.13** in order to compile with webpack.

'markReactive' appears to have been removed here: https://github.com/vuejs/composition-api/commit/f204daaab4248590e254bac06690e33e507fb0de#diff-c36c909d3a8f19854e27884759d63990fba3d4de54593dd1537d082d76770e38

**Comment by antfu** [comment]
`markReactive` isn't public for either Vue 2 and 3. Don't really see a reason why this would bother you? Can you provide more context?

**Comment by tbtalbottjr** [comment]
The problem is that my app no longer compiles under webpack because your library is trying to export 'markReactive' from @vue/composition-api, but it no longer exists since 1.0.0-beta.14:

ERROR in ./node_modules/**vue-demi**/lib/index.esm.js 18:0-488:
```
/**VCA-EXPORTS**/
export { computed, createApp, customRef, defineComponent, getCurrentInstance, h, inject, isReactive, isReadonly, isRef, markRaw, markReactive, nextTick, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onServerPrefetch, onUnmounted, onUpdated, provide, proxyRefs, reactive, ref, set, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, useCSSModule, watch, watchEffect } from '@vue/composition-api'
/**VCA-EXPORTS**/
```

Make sense?

**Comment by antfu** [comment]
It does not appear on my side.

It looks like you have multiple versions of `@vue/composition-api` installed, please update your lock and try again.

**Comment by tbtalbottjr** [comment]
Actually, it looks like there were two entries for vue: 2.6.10 & 2.6.12. I removed vue and re-added it and that seems to have solved the problem. Not sure what happened or why that showed up as an error in your library, but I will take it.

Thanks... Closing.
