### ISSUE TITLE
stop VSCode + Typescript importing vue-demi

### ISSUE THREAD

**Issue by theoephraim** [vueuse/vue-demi#57]
Not exactly an issue with the library but hoping you may be able to help.

After installing `@vueuse/core`, when VSCode + typescript shows intellisense and automatically adds imports (for example for `ref` or `computed`), it is now importing from vue-demi rather than from vue. This would make sense if I was developing a tool/library meant to be used with vue2 and vue3, but I am working on a strictly vue3 project and I'd like things to be imported from vue directly.

Any guidance on how I can tell VSCode to prefer vue instead of vue-demi?

**Comment by antfu** [comment]
For some info: https://twitter.com/youyuxi/status/1405236419900104710

**Comment by antfu** [comment]
Close as it's out-of-scope
