### ISSUE TITLE
resolveDirective, withDirectives and many other vue@3 modules are not found in vue-demi when used in vue@2 environments

### ISSUE THREAD

**Issue by gluecksmensch** [vueuse/vue-demi#60]
Imports of `resolveDirective`, `withDirectives` and many other vue@3 modules are not found in `vue-demi` when used in vue@2 environments.

```js
import {
  defineComponent,
  h,
  isVue2,
  resolveComponent,
  resolveDirective,
  withDirectives,
  vModelDynamic,
  vShow,
} from 'vue-demi';
```

In vue@2 environments this will result in an error like `"export 'withDirectives' was not found in 'vue-demi'`.

Any idea on how to handle these cases?

**Comment by antfu** [comment]
This is the limitation of @vue/composition-api, if you find any chance to back port those api back to vue 2, open PRs to https://github.com/vuejs/composition-api. Thanks
