### ISSUE TITLE
Error building after last update

### ISSUE THREAD

**Issue by miguelfspinto** [vueuse/vue-demi#63]
Hi,

After the last update for version 0.8, i cannot run build on my app:

RROR  Failed to compile with 42 errors7:36:04 PM
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'computed' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'createApp' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'customRef' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'defineComponent' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'del' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'getCurrentInstance' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'h' from non EcmaScript module (only default export is available)

**Comment by antfu** [comment]
Can't reproduce on my side, can you try a clean install or provide a minimal reproduction? Thanks

**Comment by lstoeferle** [comment]
For me it's the same error after upgrading to `v0.8`. I use it in a vue2 web-component project, where `vue` and `@vue/composition-api` are located in the devDependencies.

**Comment by antfu** [comment]
Can I have the content of `vue-demi/lib/index.esm.mjs`? Still, ideally a repro is preferred.

**Comment by lstoeferle** [comment]
Unfortunately I can not share the repo, since it belongs to the company I'm working for :( 
`vue2`, `vue-demi`, `@vue/composition-api`, `@vue/cli` (webcomponent build), `webpack`
```javascript
// vue-demi/lib/index.esm.mjs
import Vue from 'vue'
import VueCompositionAPI from '@vue/composition-api'

function install(_vue) {
  _vue = _vue || Vue
  if (_vue && !_vue['__composition_api_installed__'])
    Vue.use(VueCompositionAPI)
}

install(Vue)

var isVue2 = true
var isVue3 = false
var Vue2 = Vue
var version = Vue.version

/**VCA-EXPORTS**/
export { computed, createApp, createRef, customRef, defineAsyncComponent, defineComponent, del, getCurrentInstance, h, inject, isRaw, isReactive, isReadonly, isRef, markRaw, nextTick, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onServerPrefetch, onUnmounted, onUpdated, provide, proxyRefs, reactive, readonly, ref, set, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, useCSSModule, useCssModule, warn, watch, watchEffect } from '@vue/composition-api'
/**VCA-EXPORTS**/

export {
  Vue,
  Vue2,
  isVue2,
  isVue3,
  version,
  install,
}

```

**Comment by miguelfspinto** [comment]
Still having the same error after update 0.8.1
@antfu , i'm gonna add you to the repo. Do you have gitlab account?

error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'computed' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'createApp' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'customRef' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'defineComponent' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'del' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs
Can't reexport the named export 'getCurrentInstance' from non EcmaScript module (only default export is available)
 error  in ./node_modules/@vueuse/core/node_modules/vue-demi/lib/index.esm.mjs

**Comment by fk1blow** [comment]
i m having the same issue on osx with node v15.14.0. 
I m specifying the node version b/c the same codebase running on ubuntu with node v12.20.0 seems fine

**Comment by fedeee** [comment]
FYI: this also relates to: https://github.com/vuejs/vue-apollo/issues/1190

**Comment by antfu** [comment]
0.9.0 release. Would need some help to confirm if it's a fix. Thanks!

**Comment by fk1blow** [comment]
@antfu i m having @vueuse/core as a dependency so i could try that one specifically

**Comment by fedeee** [comment]
This seems to have fixed it for us

**Comment by JuroOravec** [comment]
@antfu 0.9.0 fixes the issue with vuejs/vue-apollo (vuejs/vue-apollo#1190), thanks!

**Comment by jzs11** [comment]
This error is coming back after upgrade to the latest

![image](https://user-images.githubusercontent.com/2770401/132657286-a2247fdc-de0a-44ef-9954-7335c0b5c869.png)

**Comment by Muchmorepig** [comment]
I met the same issue:
![image](https://user-images.githubusercontent.com/68462246/133189742-3fc5b8fe-c082-4de1-80dc-41fa7c35bf96.png)

**Comment by jzs11** [comment]
Try this - https://github.com/vueuse/vueuse/discussions/731
