### ISSUE TITLE
dependency issue with @vue/composition-api

### ISSUE THREAD

**Issue by eunjae-lee** [vueuse/vue-demi#67]
Hello, I'm working on supporting both Vue2 and Vue3 in [Vue InstantSearch](https://github.com/algolia/vue-instantsearch).

I used vue-demi inside Vue InstantSearch. After installing Vue InstantSearch in an empty project, it gives me this error:

```
 ERROR  Failed to compile with 1 error                              17:19:50

This dependency was not found:

* @vue/composition-api in ./node_modules/vue-demi/lib/index.esm.js

To install it, you can run: npm install --save @vue/composition-api
```

More details:

In the `package.json` of Vue InstantSearch, 

```js
  "dependencies": {
    "vue-demi": "^0.9.1",
    // ...
  },
  "peerDependencies": {
    "vue": "^2.6.0 || >=3.0.0-rc.0",
    "@vue/composition-api": "^1.0.0-beta.1",
    // ...
  },
  "peerDependenciesMeta": {
    "@vue/composition-api": {
      "optional": true
    }
  },
  "devDependencies": {
    "vue": "2.5.18",
    // ...
  }
```

You can see the [pull request here](https://github.com/algolia/vue-instantsearch/pull/847). And I deployed the temporary build of the pull request via CodeSandbox, which is:

https://pkg.csb.dev/algolia/vue-instantsearch/commit/3341e045/vue-instantsearch

Now I put it in an example:
[p9ez8.zip](https://github.com/vueuse/vue-demi/files/6571166/p9ez8.zip)

If you run `yarn install && yarn serve` it will show the error message above.

In Vue InstantSearch, we do not use `@vue/composition-api`, so left it as optional. The error message goes away only when I install it as a dependency inside the example.

Do you have any idea? Thanks!

- macOS: 11.3.1
- node: 12.19.0

**Comment by antfu** [comment]
`@vue/composition-api` is optional only when using Vue 3, so the user environment should be either:

- `vue@2` + `@vue/composition-api`
- `vue@3`

**Comment by eunjae-lee** [comment]
@antfu oh I didn't see that. Do you happen to have a plan to support vue@2 without composition api?

**Comment by antfu** [comment]
Currently no. `vue-demi` only make sense when using Composition API. But on the other hand, [Vue 2.7](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0038-vue3-ie11-support.md#for-those-who-absolutely-need-ie11-support) will have the `@vue/composition-api` plugin builtin, which is planned in Q3 this year.

**Comment by eunjae-lee** [comment]
@antfu Thanks for the comment. Good to know. I should write something small that does the similar thing as vue-demi.
Have a good day!

**Comment by eunjae-lee** [comment]
Do you mind if I fork this repo and remove the composition api part?
