### ISSUE TITLE
Vue instance got 'undefined' in build with Vite + library mode

### ISSUE THREAD

**Issue by sondh0127** [vueuse/vue-demi#69]
Error: "TypeError: Cannot read property 'observable' of undefined"
![image](https://user-images.githubusercontent.com/62163604/122397883-90269a80-cfa3-11eb-9bd0-b130bcbf517f.png)

I try to create a component for Vue3/2 with (vue-demi + Vite2) .
First, I'm focusing with Vue 2 setup, It's work fine in demo with directed import, but got error when in bundled lib (vite build)
![image](https://user-images.githubusercontent.com/62163604/122398763-63bf4e00-cfa4-11eb-800e-7f4490ff3d3c.png)
[https://github.com/sondh0127/vite-vue2-demi-reproduction/blob/d18773916b65c553c41c93b5823a4d797bcd0170/demo/App.vue#L11](https://github.com/sondh0127/vite-vue2-demi-reproduction/blob/d18773916b65c553c41c93b5823a4d797bcd0170/demo/App.vue#L11)

Please take a look. Here is my vite config.
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { createVuePlugin } from 'vite-plugin-vue2'
import WindiCSS from 'vite-plugin-windicss'
import path from 'path'

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		// vue(),
		createVuePlugin({}),
		// WindiCSS(),
	],
	resolve: {
		alias: {
			'@': `${path.resolve(__dirname, 'src')}`,
		},
		dedupe: ['vue-demi'],
	},
	build: {
		lib: {
			name: 'VueInteractive',
			entry: path.resolve(__dirname, 'src/main.ts'),
		},
		minify: false,
		rollupOptions: {
			external: ['vue'],
			output: {
				globals: {
					vue: 'Vue',
				},
			},
		},
	},

	optimizeDeps: {
		exclude: ['vue-demi'],
	},
})
```

Reproduction: [https://github.com/sondh0127/vite-vue2-demi-reproduction](https://github.com/sondh0127/vite-vue2-demi-reproduction)

**Comment by sondh0127** [comment]
Look like the problem comes from composition api package. @antfu can you take a look ? Thanks

**Comment by antfu** [comment]
External `vue-demi` and add it to your lib's dep. Please note the vdom is different between Vue 2 and 3, while `vue-demi` only handles the composition api and package redirecting, the compiled Vue file can't not work isomorphically. I'd actually suggest you to publish the vue file directly to npm and let userland compiler to handle it.
