### ISSUE TITLE
Node.js ESM export support

### ISSUE THREAD

**Issue by pi0** [vueuse/vue-demi#71]
Hi :) Trying `vue-demi` (as a dependency of `vue-global-api`) on latest nuxt3 version, production build fails since there is no `import` matcher. (and currently [node condition](https://github.com/vueuse/vue-demi/blob/master/package.json#L16) is set to cjs)

> Could not resolve import "vue-demi" in ..../node_modules/vue-global-api/onActivated.mjs using exports defined in ..../node_modules/vue-demi/package.json

It can be fixed by adding `import` field to package.json: (should be ideally esm build)

```diff
  "exports": {
    ".": {
      "require": "./lib/index.cjs.js",
++   "import": "./lib/index.cjs.js",
      "node": "./lib/index.cjs.js",
      "browser": "./lib/index.esm.js"
    },
    "./*": "./*"
  },
```

- Note: I think it would be much better if you tend to use explicit `.mjs` and `.cjs` extensions so that tooling can infer module type.
- Note: SSR vs Node: `node` condition can be added to niro resolver but since there are also non Node.js SSR environments (like Cloudflare workers) we would need import only support

**Comment by dragomirweb** [comment]
![image](https://user-images.githubusercontent.com/29796024/125824596-4d52481d-684d-4ffd-8d85-71f88408d249.png)
your fix worked
