### ISSUE TITLE
v 0.11.1 causes issues to vue-use

### ISSUE THREAD

**Issue by fk1blow** [vueuse/vue-demi#73]
we re using @vueuse/core 5.0.3 and the latest update to vue demi, breaks our build(which was fine a few hours ago).
We re not using vue-demi directly, only through vueuse.

```
 error  in ./node_modules/vue-demi/lib/index.mjs

Can't reexport the named export 'computed' from non EcmaScript module (only default export is available)
```

we re seeing a bunch of these, not only "computed"; everything exported from vue-demi causes this issue.

**Comment by dragomirweb** [comment]
same for me !

**Comment by fk1blow** [comment]
This might be regression, one that we encountered a couple of versions back

**Comment by Demivan** [comment]
Is it broken in 0.11.0 too? 0.11.1 should not affect it.

**Comment by antfu** [comment]
You can provide more context, what vue version and what build tools?

**Comment by fk1blow** [comment]
vueuse depends on vue-demi with `"vue-demi": "^0.9.1",` so that might be it.

We ran a build ~2hrs ago and everything worked fine. 30 mins back, after a build attempt, we started seeing these errors all of a sudden. Nothing changed in our build system so this is the only thing that might cause it to fail

**Comment by fk1blow** [comment]
@antfu we can't provide a git repo.

"vue": "^2.6.10",
"@vueuse/core": "^5.0.3"

**Comment by antfu** [comment]
Vite or Vue CLI?

**Comment by fk1blow** [comment]
vue cli

**Comment by antfu** [comment]
Should be good now with v0.11.2
