### ISSUE TITLE
Support Vue 3.2 

### ISSUE THREAD

**Issue by 3zzy** [vueuse/vue-demi#83]
Doesn't look like 3.2 has too many breaking changes so wondering if `vue-demi` could support 3.2 already?

```
npm ERR! Found: vue@3.2.0-beta.6
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.0-beta.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^3.0.2" from vuex@4.0.2
npm ERR! node_modules/vuex
npm ERR!   vuex@"^4.0.0-rc.2" from the root project
```

**Comment by 3zzy** [comment]
My app is entirely based on Vue 3 composition API and uses Vue 3 compatible plugins so I don't even need Vue-Demi I suppose but since I use VueUse its a dependency. Please look into making it optional if possible.

**Comment by antfu** [comment]
vue-demi is just a redirection layer that does not care about the actual implementation of vue, it should works fine as always with vue 3.2. It's probably your local install issues.
