### ISSUE TITLE
How to close warning "export 'withDirectives' (imported as 'i') was not found in 'vue-demi'" in vue2?

### ISSUE THREAD

**Issue by Shimada666** [vueuse/vue-demi#94]
the issue is like this #60 .
I use different h function in vue2 and vue3.
```javascript
if (isVue3) {
      const highlight = resolveDirective('highlight')
      return withDirectives(h('div', {
        innerHTML: this.html
      }), <DirectiveArguments>[
        [highlight]
      ])
    } else {
      return h('div', {
        domProps: {
          innerHTML: this.html
        },
        directives: [
          {
            name: 'highlight'
          }
        ]
      })
    }
```
But when I use vue2, it has a warning
`export 'withDirectives' (imported as 'i') was not found in 'vue-demi'`
How to resolve it? I just want to close the warning in dev console.

**Comment by antfu** [comment]
This is not part of the Composition API and @vue/composition-api does not have a equivalent.
