### ISSUE TITLE
Outdated Dependency: update package.json for composition api

### ISSUE THREAD

**Issue by hikariNTU** [vueuse/vue-demi#95]
Problem
---

The newly introduced setup helper `useSlots` and `useAttrs` was add in VCA with version `1.1.2`
But the current `vue-demi` peerDependencies still requiring outdated `^1.0.0-rc.1`

Reproduce
---

**npm**: `0.7.x` (for auto peer install)
**node**: `14.x.x LTS`
**vue-demi**: `0.11.3`
**@vue/composition-api**: `1.1.1` (installed automatedly by npm@7 before)

```text
 error  in ./node_modules/vue-demi/lib/index.mjs
"export 'useAttrs' was not found in '@vue/composition-api/dist/vue-composition-api.esm.js'
 error  in ./node_modules/vue-demi/lib/index.mjs
"export 'useSlots' was not found in '@vue/composition-api/dist/vue-composition-api.esm.js'
```

** Notice that VCA `1.1.1` is still legit for `^1.0.0-rc.1`

Potential Solution
---
update `package.json` for VCA to `"@vue/composition-api": "^1.1.2",`

**Comment by antfu** [comment]
`vue-demi` is just a redirection layer and does not have opinion on the actually version of the plugin. "@vue/composition-api" is placed as "peerDeps" and marked optional, which means npm won't install it for you and you have to manage the version yourself separately.

**Comment by hikariNTU** [comment]
But I think this export explicitly requires the existence of `useAttrs` and `useSlots` from VCA
```js
/**VCA-EXPORTS**/
export { useAttrs, useSlots } from '@vue/composition-api/dist/vue-composition-api.esm.js'
/**VCA-EXPORTS**/
```

Is there anything that we can improve to make it warn about missing redirect target instead of throw error in something like webpack enviroment?

BTW npm@7 does install peerDependencies if you don't install them in your project.

**Comment by antfu** [comment]
It generate the exports based on your local installs. Make sure you don't have multiple versions of the plugin in your node_modules
