### ISSUE TITLE
export default was not found in 'vue'.

### ISSUE THREAD

**Issue by Zony-Zhao** [vueuse/vue-demi#97]
It seems somehow vue2 is not resolved  in vue-demi.
###Env:###
I make the lib dependency same as readme recommended.
And the project using the lib is in vue 3.0.0.
here is the library package.json:
![image](https://user-images.githubusercontent.com/50739849/131457966-6c60db84-0456-4d71-b0f6-018799ee0711.png)

 ###Error:###
 error  in ../tools/gei-framework/node_modules/vue-demi/lib/index.mjs

"export 'default' (reexported as 'Vue') was not found in 'vue'.

**Comment by antfu** [comment]
Try `npx vue-demi-fix`

**Comment by Zony-Zhao** [comment]
still persists. @antfu

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by Zony-Zhao** [comment]
I delete node_modules and reinstalled. Here is what I got:
![image](https://user-images.githubusercontent.com/50739849/131480126-5c7cf7f6-9030-4010-8a80-e8f169874049.png)

**Comment by Zony-Zhao** [comment]
It turns out to be pretinstalled package confilcting with package.json config. Closing it.
